source 'https://github.com/lightningkite/cocoapods-spec-repo.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
use_frameworks!
use_modular_headers!

inhibit_all_warnings!

target 'DKImagePickerControllerDemo' do

  pod 'DKImagePickerController', :path => '../'

  # Pods for DKImagePickerControllerDemo

  target 'DKImagePickerControllerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
